server:
  port: 8093

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/

spring:
  application:
    name: service-ticket